In [16]:
import random

a = random.random()
print(a)

a = random.uniform(1, 10)
print(a)

# include upper bound
b = random.randint(1, 10)
print(b)

# not include upper bound
b = random.randrange(1, 10)
print(b)

# normal rand num
c = random.normalvariate(0, 1)
print(c)

0.6944596026555593
5.857686365918436
3
4
1.6057411759395215


In [21]:
mylist = list("ABCDDEFGH")
a = random.choice(mylist)
print(a)

B


In [24]:
a = random.choices(mylist, k=3)
print(a)

['E', 'G', 'D']


In [27]:
random.shuffle(mylist)
print(mylist)

['B', 'C', 'H', 'A', 'D', 'F', 'D', 'E', 'G']


# Reprod rand nums

In [28]:
random.seed(1)
print(random.random())
print(random.uniform(1, 10))
print(random.randint(1, 10))
print(random.randrange(1, 10))
print(random.normalvariate(0, 1))

0.13436424411240122
8.626903632435095
2
5
-0.07674923238392503


In [29]:
random.seed(1)
print(random.random())
print(random.uniform(1, 10))
print(random.randint(1, 10))
print(random.randrange(1, 10))
print(random.normalvariate(0, 1))

0.13436424411240122
8.626903632435095
2
5
-0.07674923238392503


# For security stuff
Use for security stuff like account logining, and so on

In [30]:
import secrets

In [31]:
a = secrets.randbelow(10)
print(a)

a = secrets.randbits(4)
print(a)

3
11


In [32]:
mylist = list("ABCDEFGH")
a = secrets.choice(mylist)
print(a)

H


# Rand by numpy

In [33]:
import numpy as np

In [35]:
print(np.random.rand(3))

[0.2047673  0.69002618 0.31806483]


In [37]:
print(np.random.rand(3, 3))

[[0.88062336 0.4666815  0.28495808]
 [0.89411452 0.74692929 0.07832614]
 [0.98132154 0.5509874  0.04645548]]


In [38]:
print(np.random.randint(0, 10))

5


In [39]:
print(np.random.randint(0, 10, 3))

[2 6 8]


In [40]:
print(np.random.randint(0, 10, (3, 2)))

[[9 0]
 [3 5]
 [8 1]]


In [41]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
np.random.shuffle(arr)
print(arr)

[[7 8 9]
 [1 2 3]
 [4 5 6]]


In [43]:
np.random.seed(1)
print(np.random.rand(3, 3))
np.random.seed(1)
print(np.random.rand(3, 3))

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
